name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: List files in root directory
      run: dir
    - name: Change to project directory and list files
      run: |
        cd HelloWorldApp
        dir
    - name: Restore dependencies
      run: |
        cd HelloWorldApp
        dotnet restore
    - name: Build
      run: |
        cd HelloWorldApp
        dotnet build --configuration Release --no-restore
    - name: Verify .NET SDK version
      run: dotnet --version

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Change to project directory and list files
      run: |
        cd HelloWorldApp
        dir
    - name: Run unit tests
      run: |
        cd HelloWorldApp
        dotnet test --no-build --verbosity normal

  deploy:
    runs-on: windows-latest
    needs: test
    steps:
    - name: Deploy application
      run: |
        echo "Deployment logic goes here"
    - name: Send email notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: "Build/Deployment Failed"
        body: "The recent CI/CD pipeline failed. Please check the logs for details."
        to: duanevanappel@gmail.com
        from: ${{ secrets.GMAIL_USERNAME }}

