name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3  # Updated to v3
        with:
          dotnet-version: '7.x'  # Update to your .NET version

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Deploy
        run: echo "Deploy stage - Add your deploy commands here"
        # Replace with actual deployment commands or actions if needed
